### ISSUE TITLE
Should check error first

### ISSUE THREAD

**Issue by leedstyh** [ShawnRong/tushare-go#1]
我的这段代码出错了：
```
	data, err := api.Daily(params, fields)
```

错误信息是：
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x6a0087]

goroutine 1 [running]:
github.com/ShawnRong/tushare-go.(*TuShare).doRequest(0xc00007dee0, 0xc000190000, 0x0, 0x0, 0x0)
        D:/Software/gopath/pkg/mod/github.com/!shawn!rong/tushare-go@v0.0.0-20190319090429-7a1ec052b215/client.go:53 +0x157
github.com/ShawnRong/tushare-go.(*TuShare).postData(0xc00007dee0, 0xc00006d6e0, 0x73ca6a, 0x6, 0xc00013ed18)
        D:/Software/gopath/pkg/mod/github.com/!shawn!rong/tushare-go@v0.0.0-20190319090429-7a1ec052b215/client.go:104 +0x9d
github.com/ShawnRong/tushare-go.(*TuShare).Daily(0xc00007dee0, 0xc00006d620, 0xc0000482a0, 0x6, 0x6, 0xd, 0x7af4e0, 0xc00003ce20)
        D:/Software/gopath/pkg/mod/github.com/!shawn!rong/tushare-go@v0.0.0-20190319090429-7a1ec052b215/market_data.go:27 +0x401
stocks/go/quant.RequestOHLCV(0x73ebff, 0x9, 0x0, 0x0, 0x0)
        D:/Code/stocks/go/quant/tushare.go:25 +0x233
main.testTushare()
        D:/Code/stocks/go/quant/cmd/main.go:52 +0x3d
main.main()
        D:/Code/stocks/go/quant/cmd/main.go:13 +0x27
exit status 2
```

我检查了下client.go的代码，[这里](https://github.com/ShawnRong/tushare-go/blob/master/client.go#L51-L60)：
```
	resp, err := api.client.Do(req)
	//Handle network error
	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("oops! Network error")
	}

	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
```

是不是应该先检查err，再调用resp？

**Comment by ShawnRong** [comment]
感谢指出错误， 已经push最新的更新

**Comment by ShawnRong** [comment]
如果还有好的建议 可以开PR🙂
